### ISSUE TITLE
[FR] Allow to attach image

### ISSUE THREAD

**Issue by SpotlightKid** [OpenMusicKontrollers/notes.lv2#1]
As discussed on IRC, it would be great if one could attach an image to the notes, and it's path would be saved in the plugin state.

It would be useful e.g. for those working with hardware synths without preset memory. You'd just attach a phone snapshot of the controls. Or it could be used to attach handwritten performance notes. 

The plugin could display the image in its own UI and/or provide a button to launch an external image viewer. The latter might be preferable as an option no matter what, because an image viewer of choice may provide useful functions like panning, zooming, rotating, cropping etc.

**Comment by ventosus** [comment]
thanks for the request.

supported starting from f1d9e81b9dd8e9e08aa785175c13c7d92b98dd83

feel free to give it a go.

instead of opening in external application, there's support to copy text and/or image to the clipboard - more likely to work everywhere on setups that miss xdg-open et. al.

**Comment by trebmuh** [comment]
![notes lv2-load_an_image](https://user-images.githubusercontent.com/8705846/94349547-948dda80-0045-11eb-9d3c-9107cf563780.png)

**Comment by SpotlightKid** [comment]
Probably not related, but I'll report it anyway:

```
$ ninja test
[0/1] Running all tests.
1/9 d2tk / Test core            OK             0.68s
2/9 d2tk / Test base            OK             1.43s
3/9 d2tk / FiraSans-Bold.ttf    FAIL           0.08s (exit status 1)
4/9 d2tk / FiraCode-Light.ttf   OK             0.13s
5/9 d2tk / FiraCode-Regular.ttf OK             0.13s
6/9 d2tk / FiraCode-Medium.ttf  OK             0.12s
7/9 d2tk / FiraCode-Bold.ttf    OK             0.13s
8/9 notes.lv2 / LV2 validate    OK             0.28s
9/9 notes.lv2 / LV2 lint        OK             0.43s

Ok:                 8   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   


The output from the failed tests:

3/9 d2tk / FiraSans-Bold.ttf    FAIL           0.08s (exit status 1)

--- command ---
20:35:41 /home/chris/src/notes.lv2/subprojects/d2tk/check_for_font FiraSans-Bold.ttf
-------

Full log written to /home/chris/src/notes.lv2/build/meson-logs/testlog.txt
FAILED: meson-test 
/usr/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
```

**Comment by SpotlightKid** [comment]
I also get a segfault when the plugin is closed (using jalv.gtk as a host).

In Carla, I get this warning in the Log tab:

```
lv2_rdf_new("http://open-music-kontrollers.ch/lv2/notes#notes") - got unknown unit 'http://open-music-kontrollers.ch/lv2/notes#px'
```

**Comment by SpotlightKid** [comment]
It would also be nice, if the plugin remembered the last used directory for the file dialog, if possible, at least during the same session.

**Comment by ventosus** [comment]
@trebmuh remember me telling you "you won't have image *loading* support with lv2 < 1.18.0" :-)

That's that. I won't write my own file chooser dialog thingy and instead rely on the host to show its own. That's feature is only in LV2 1.18.0

**Comment by ventosus** [comment]
@trebmuh, see the failing test @SpotlightKid posted, you're missing the given system font *FiraSans-Bold.ttf*.

If you don't want to rely on system fonts, you can embed it in the plugin bundle by just disabling fontconfig support.

    cd build && meson configure -Duse-fontconfig=disabled

**Comment by ventosus** [comment]
@SpotlightKid 

> In Carla, I get this warning in the Log tab:

Ignore it, it is just a custom parameter unit carla does not know about, does no harm.

**Comment by ventosus** [comment]
@trebmuh, loading button is also not shown, if the host does not support the new host-open-dialog features (e.g. jalv.gtk does not, iirc).

**Comment by ventosus** [comment]
> It would also be nice, if the plugin remembered the last used directory for the file dialog, if possible, at least during the same session.

the file dialog is the host's responsibility, file a feature request there :-) Nothing the plugin can do about.

**Comment by SpotlightKid** [comment]
> If the host does not support the new host-open-dialog features (e.g. jalv.gtk does not, iirc).

It does.

> a custom parameter unit carla does not know about, does no harm.

I didn't know you were allowed to do that. ;)

>  the file dialog is the host's responsibility

I suspected as much. At least the GTK/Qt file selection dialogs give access to the bookmarks.

> you're missing the given system font FiraSans-Bold.ttf

Ok, I had FiraCode installed, but not FiraSans. This should be mentioned in the requirements in the readme

**Comment by SpotlightKid** [comment]
> instead of opening in external application, there's support to copy text and/or image to the clipboard

This works, but I think it's not very convenient. To open the image in another program with a simple action, I have to run something complex like:

    fn="$(mktemp -t xlip.XXXXXX)" && xclip -selection clipboard -t image/jpeg -o >"$fn" && sxiv "$fn"

(which took me about 15 minutes to figure out how to do correctly) and then put that in a script or bind it to a key. Not ideal.

**Comment by trebmuh** [comment]
> @trebmuh remember me telling you "you won't have image loading support with lv2 < 1.18.0" :-)

This one has been built with 1.18.0 so it shoudl'nt be the issue here I think.



> @trebmuh, see the failing test @SpotlightKid posted, you're missing the given system font FiraSans-Bold.ttf.

Cool about the missing ttf, I'll rebuilding it adding that build-dep so. BTW, there isn't any check for that in the configure step, isn't?



>@trebmuh, loading button is also not shown, if the host does not support the new host-open-dialog features (e.g. jalv.gtk does not, iirc).

OK, I'll try with other hosts since I've been using jalv.gtk so far. Any recommendation maybe?


Thanks for your answers.

**Comment by ventosus** [comment]
@SpotlightKid 

>> If the host does not support the new host-open-dialog features (e.g. jalv.gtk does not, iirc).
> It does.

jalv from git does not count, sorry :-)

> I have to run something complex like
nice one.

there's an *open* button now starting from 40199c795ae8c0e8c7ec5c4cb8729a2fb589b6d3 calling xdg-open ...

**Comment by ventosus** [comment]
@trebmuh 

> Cool info about the missing ttf, I'll rebuilding it adding that build-dep so. BTW, there isn't any check for that in the configure step, isn't?

Not explicitely, will be added once there will be an official release, thanks for mentioning it.

It's not a build dependency, it's a runtime dependency, so it is checked for in the unit tests - and yes, those are mentioned in the build steps (ninja test).

**Comment by SpotlightKid** [comment]
> there's an open button now starting from 40199c7 calling xdg-open ...

Thanks for that, but unfortunately Carla doesn't like it: :frowning_face: 

```
Carla prevented a plugin from calling 'fork', bad plugin!
/usr/bin/xdg-open: fork: Die angeforderte Funktion ist nicht implementiert
Carla prevented a plugin from calling 'exit', redirecting to '_exit' instead, bad plugin!
```

**Comment by ventosus** [comment]
@SpotlightKid thanks for reporting. On what *nix system are you (GNU/Linux, BSD ...) ? The UI should use *clone*, if not on GNU/Linux, it should use vfok, if not available it would indeed fall back to fork.

Can you paste the output of *meson build* please ? It should autodiscover what your system supports.

**Comment by SpotlightKid** [comment]
Carla apparently disables not only `fork`, but also `clone` and others:

https://github.com/falkTX/Carla/blob/8b7203135811064aa7eaae5c1b152398cc81610b/source/interposer/interposer-safe.cpp#L38
 
```
$ uname -a
Linux denkbett 5.8.11-lqx1-2-lqx #1 ZEN SMP PREEMPT Thu, 24 Sep 2020 14:58:07 +0000 x86_64 GNU/Linux

$ cat /etc/lsb-release 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.1
DISTRIB_CODENAME=Mikah
DISTRIB_DESCRIPTION="Manjaro Linux"

$ meson --prefix=/usr -Duse-fontconfig=disabled build
The Meson build system
Version: 0.55.3
Source dir: /home/chris/src/notes.lv2
Build dir: /home/chris/src/notes.lv2/build
Build type: native build
Project name: notes.lv2
Project version: undefined
Using 'CFLAGS' from environment with value: '-march=native -O2 -pipe -fstack-protector-strong -fno-plt'
Using 'LDFLAGS' from environment with value: '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'
Using 'CPPFLAGS' from environment with value: '-D_FORTIFY_SOURCE=2'
Using 'CFLAGS' from environment with value: '-march=native -O2 -pipe -fstack-protector-strong -fno-plt'
Using 'LDFLAGS' from environment with value: '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'
Using 'CPPFLAGS' from environment with value: '-D_FORTIFY_SOURCE=2'
C compiler for the host machine: ccache cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35
Host machine cpu family: x86_64
Host machine cpu: x86_64

|Executing subproject d2tk method meson 
|
|Project name: d2tk
|Project version: undefined
|C compiler for the host machine: ccache cc (gcc 10.2.0 "cc (GCC) 10.2.0")
|C linker for the host machine: cc ld.bfd 2.35
|Program grep skipped: feature use-fontconfig disabled
|Program fc-list skipped: feature use-fontconfig disabled
|Program check_for_font skipped: feature use-fontconfig disabled
|Library m found: YES
|Dependency freetype2 skipped: feature use-backend-cairo disabled
|Dependency pixman-1 skipped: feature use-backend-cairo disabled
|Dependency cairo skipped: feature use-backend-cairo disabled
|Dependency cairo-xlib skipped: feature use-backend-cairo disabled
|Dependency libinput skipped: feature use-frontend-fbdev disabled
|Dependency libudev skipped: feature use-frontend-fbdev disabled
|Dependency libevdev skipped: feature use-frontend-fbdev disabled
|Found pkg-config: /usr/bin/pkg-config (1.7.3)
|Run-time dependency glu found: YES 9.0.1
|Run-time dependency glew found: YES 2.2.0
|Library util found: YES
|Run-time dependency vterm found: YES 0.1.3
|Dependency libevdev skipped: feature use-evdev disabled
|Dependency fontconfig skipped: feature use-fontconfig disabled
|Checking for function "vfork" : YES 
|Checking for function "clone" : YES 
|Run-time dependency gl found: YES 1.2
|Run-time dependency x11 found: YES 1.6.12
|Run-time dependency xext found: YES 1.3.4
|Configuring config.h using configuration
|Build targets in project: 2
|Subproject d2tk finished.

Program lv2_validate found: YES
Program sord_validate found: YES
Program lv2lint found: YES
Library m found: YES
Run-time dependency lv2 found: YES 1.18.1
Checking whether type "LV2UI_Request_Value" has member "request" : YES 
Message: building with ui:requestValue support
Configuring manifest.ttl using configuration
Build targets in project: 4

notes.lv2 undefined

  Subprojects
    d2tk: YES

Found ninja-1.10.1 at /usr/bin/ninja

$ ninja -C build -j4                                                        
ninja: Entering directory `build'
[90/91] Compiling C object notes_ui.so.p/notes_ui.c.o
../notes_ui.c: In Funktion »_file_read«:
../notes_ui.c:1048:2: Warnung: Der Rückgabewert von »read«, der mit dem Attribut »warn_unused_result« deklariert wurde, wird ignoriert [-Wunused-result]
 1048 |  read(handle->fd, txt, txt_len);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../notes_ui.c: In Funktion »_expose_image_copy«:
../notes_ui.c:402:3: Warnung: Der Rückgabewert von »read«, der mit dem Attribut »warn_unused_result« deklariert wurde, wird ignoriert [-Wunused-result]
  402 |   read(fd, buf, buf_len);
      |   ^~~~~~~~~~~~~~~~~~~~~~
[91/91] Linking target notes_ui.so

$ ninja -C build test
ninja: Entering directory `build'
[0/1] Running all tests.
1/4 d2tk / Test core         OK             0.73s
2/4 d2tk / Test base         OK             1.49s
3/4 notes.lv2 / LV2 validate OK             0.28s
4/4 notes.lv2 / LV2 lint     OK             0.53s

Ok:                 4   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/chris/src/notes.lv2/build/meson-logs/testlog.txt
```

**Comment by SpotlightKid** [comment]
Ooops, I just discovered there's a special option for that in Carla's settings, which I had enabled.

After de-activating the setting and restarting Carla, opening the external image viewer works!


![Carla-unsafe-setting](https://user-images.githubusercontent.com/5719151/94375949-8c05d480-0117-11eb-88fe-a5e1a5802af0.png)

**Comment by ventosus** [comment]
@SpotlightKid look good.

What is your lv2lint version ?

Tested it here and it just works, cannot reproduce, maybe @falktk know

    $ carla --version
    Using Carla version 2.1.1
      Python version: 3.8.5
      Qt version:     5.15.1
      PyQt version:   5.15.1
      Binary dir:     /usr/lib/carla
      Resources dir:  /usr/share/carla/resources

**Comment by ventosus** [comment]
@SpotlightKid well, this is strange, clone is also called for the embedded console editor, so the warning should already have gone off there and not only for invoking *xdg-open*.

**Comment by SpotlightKid** [comment]
Yeah, strange. The editor (nano in my case) works.

**Comment by trebmuh** [comment]
>>@trebmuh, loading button is also not shown, if the host does not support the new host-open-dialog features (e.g. jalv.gtk does not, iirc).

> OK, I'll try with other hosts since I've been using jalv.gtk so far.

I've tried in other hosts and it seems it works in carla 2.1.1 and doesn't work in Qtractor 0.9.17 not in Ardour 6.3.

Note that using the `-Duse-fontconfig=disabled` worked for me now, awesome!

![notes-lv2-all-good](https://user-images.githubusercontent.com/8705846/94381132-88367a00-0138-11eb-9fa2-f3a54418ac34.png)

Everything looks good for me now, thank you very much for your help.

**Comment by ventosus** [comment]
@trebmuh 

> I've tried in other hosts and it seems it works in Carla 2.1.1 (and doesn't work in Qtractor 0.9.17 not in Ardour 6.3).

Qtractor does not let user choose the notes plugin, because it does neither contain MIDI nor AUDIO ports, nothing I can do about. I don't feel like adding fake MIDI and/or AUDIO ports, seems just wrong.

What does not work in Ardour ? I'm running 6.3, too, here, and apart from *loading text* everything seems to work.

> Note that using the -Duse-fontconfig=disabled worked for me, awesome!

great, this will also be the default upon release, enabling fontconfig support is mainly meant for distribution packagers which usually don't like emedded fonts.

**Comment by trebmuh** [comment]
OK about Qtractor, thanks for the info.

About Ardour 6.3:
- I can't make a "space character" since pushing the space bar launch playing in Ardour
- I can't  push Enter since it rewind Ardour's playhead
- the A, L, W, ",", and the "^" keys are not working
- the load buttons are not there (so can't load an image)

**Comment by ventosus** [comment]
@trebmuh there's a keyboard icon in the top right of ardour's parent UI window. Press it, and ardour will stop intercepting your keystrokes :-)

**Comment by ventosus** [comment]
@trebmuh if the load buttons are not there, then your version of ardour does not give access (or does not support) the requestValue extension [1]. Nothing I can do about, sorry. I'm running Ardour 6.3, too (Parabola), image load button works fine here.

[1] http://lv2plug.in/ns/extensions/ui#requestValue

**Comment by trebmuh** [comment]
Rebuilding ardour against lv2 1.18 fixed it.
Thanks for the tip about the "keyboard icon in the top right of ardour's parent UI window", everything is working now.
