### ISSUE TITLE
[FR] Display image file name (basename) in the image pane

### ISSUE THREAD

**Issue by SpotlightKid** [OpenMusicKontrollers/notes.lv2#3]
For example after the "Image" label.

**Comment by ventosus** [comment]
thanks, for the request, added in fbd20ae186f192db4fcc668cbba822e4ddce625b

**Comment by SpotlightKid** [comment]
Looks good. Thank you!

**Comment by ventosus** [comment]
has been redesigned in the meantime, basename has become a link, clicking it, opens it in external application.
