### ISSUE TITLE
closing the plugin's GUI crashes ardour 6.3

### ISSUE THREAD

**Issue by trebmuh** [OpenMusicKontrollers/notes.lv2#4]
When closing the plugin's GUI in Ardour 6.3, it makes Ardour crashing.
Starting from a terminal is only giving a "segfault" line.

**Comment by ventosus** [comment]
@trebmuh thanks for reporting, this is a known issue, all my *terminal-embedding* plugin UI's have that issue on ardour. It's likely a bug in ardour, the latter intercepts the SIGINT signal destined for the embedded editor (nano, vi, emacs, ...).

**Comment by trebmuh** [comment]
ok

**Comment by ventosus** [comment]
reported upstream [1]

[1] https://mantis.ardour.org/view.php?id=8427

**Comment by ventosus** [comment]
@trebmuh a bug in the plugin's ui after all, fixed in 259447b08a73cbd071ae45e4f57be2e49ff666a6

**Comment by trebmuh** [comment]
Awesome, it doesn't crash ardour 6.3 anymore.
Thanks Ventosus.
