### ISSUE TITLE
UI crash if referenced image file in lv2 state does not exist

### ISSUE THREAD

**Issue by falkTX** [OpenMusicKontrollers/notes.lv2#6]
notes.lv2 is up-to-date to latest git.

when opening the UI and the image file the lv2 state references does not exist, notes.lv2 will crash.

**Comment by ventosus** [comment]
thanks for reporting.

cannot reproduce this, there's a check for that [1] and it work here.

[1] https://github.com/OpenMusicKontrollers/notes.lv2/blob/master/subprojects/d2tk/src/backend_nanovg.c#L785
