### ISSUE TITLE
Any chance of some midi steganography?

### ISSUE THREAD

**Issue by stivb** [OpenMusicKontrollers/notes.lv2#8]
I am a mod dwarf user.  I find the notes really useful.  But what I'd really like would be if I could view them during performance (remind me of lyrics, notes on the system state etc).  Would it be possible for the notes to receive a midi note (maybe prespecified in the UI - say 127 on channel 13).  When it receives that note, it sends out a midi stream of note_offs of midi notes from the ascii characters in the character buffer - potentially with some start transmission end transmission codes at the start and end.  Then in a small smart watch style screen on the guitar, I could read the notes.

I think I might eventually be able to program this myself - but am at the very early states of lv2 programming self-learning and so not confident enough right now

**Comment by ventosus** [comment]
Hi, that's out-of-scope for the notes.lv2 plugin.

But what you want should be possible with https://open-music-kontrollers.ch/lv2/moony/
